amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 5.0
    laser_max_range: 25.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    set_initial_pose: False
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.z: 0.0
    initial_pose.yaw: 0.00
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1
    recovery_alpha_slow: 0.001
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: False
    transform_tolerance: 1.0
    update_min_a: 0.1
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    always_reset_initial_pose: False
    scan_topic: scan
    map_topic: map

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery_sgd.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "sgd_ctrl::SgdProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 30.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 2.0
      yaw_goal_tolerance: 0.5
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2
      lookahead_dist: 1.0
      min_lookahead_dist: 0.6
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.1
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.1
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 0.05
      max_robot_pose_search_dist: 10.0
      use_interpolation: true

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.7
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.7
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "lohmuehlenpark.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    plugins: ["GridBased"]
    use_sim_time: False
    GridBased:
      plugin: "sgd_ctrl::LocalPlanner"
      interpolation_resolution: 0.1
      radius: 0.5

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["backup", "wait"]
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.5
    min_rotational_vel: 0.2
    rotational_acc_lim: 1.6

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

subsum_controller:
  ros__parameters:
    use_sim_time: False
    move_topics: ["cmd_vel_master", "cmd_vel_lidar", "cmd_vel_frsky", "cmd_vel"]
    sgd_move_topic: "sgd_move_base"
    
ros2_obstacle_checker:
  ros__parameters:
    use_sim_time: False
    scan_topic: "scan"
    cmd_vel_contr_topic: "cmd_vel"
    sgd_move_topic: "cmd_vel_lidar"

osm_planner:
  ros__parameters:
    use_sim_time: False
    waypoints_topic: "global_plan"
    clicked_point_topic: "clicked_point"
    yaml_filename: "lohmuehlenpark.yaml"

visualizer:
  ros__parameters:
    use_sim_time: False
    topics: ["uwb/local", "gps_local"]

### Hardware parameters ###
sick_scan2:
  ros__parameters:
    use_sim_time: False
    hostname : "141.22.33.150"
    frame_id : "base_scan"
    scanner_name : "sick_tim_5xx"
    port : 2112
    min_ang : -2.35619449
    max_ang : 2.35619449

ublox6_gps:
  ros__parameters:
    use_sim_time: False
    log_dir: ".ros/log/"
    log_severity: 4
    port: "/dev/serial/by-id/usb-u-blox_AG_-_www.u-blox.com_u-blox_GNSS_receiver-if00"
    parser_file: "/home/pascal/dev_ws/src/ros2-sgd4.0/sgd_bringup/config/nmea.xml"
    parser_type: "nmea"
    publish_local_pose: True
    publish_tf: False

frsky_rx8r:
  ros__parameters:
    use_sim_time: False
    port: "/dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_5573530323435111D172-if00"
    max_vel: 1.0
    max_rot_vel: 0.5

wh_fcruiser:
  ros__parameters:
    use_sim_time: False
    port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"
    odom_topic: "odom"
    odom_sim_topic: "odom"
    battery_state_topic: "battery"
    vel_twist_topic: "sgd_move_base"
    wheel_separation: 0.71
    wheel_circumference: 0.68
    sim_battery_state: 37.0
    relative: True

uwb_node:
  ros__parameters:
    use_sim_time: False
    log_dir: ".ros/log/"
    log_severity: "I"
    port: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10KFTNY-if00-port0"
    tag_defs: "uwb_tag_defs.yaml"
    publish_wgs84_pose: False

feather_handle_ros:
  ros__parameters:
    use_sim_time: false
    port: "/dev/serial/by-id/usb-Adafruit_Feather_M0_C9F072FA50525151322E3120FF0B1C13-if00"
    imu_topic: "imu"
    imu_temp_topic: "imu/temp"
    sgd_move_topic: "cmd_vel_laser"
    cmd_vel_topic: "cmd_vel"

led_strip:
  ros__parameters:
    port: "/dev/serial/by-id/usb-Adafruit_Feather_M0_FAE285E450533830332E3120FF171343-if00"
    