# Compute path to the goal pose

string username

# id of destination node
string dest_id

---
# Array of poses from start to goal if one was successfully found.
geometry_msgs/Point[] waypoints

# Length of path in m
float32 length