version: "3.9"

services:
  webdev:
    tty: true
    env_file:
      - .env
    build:
      context: ./visualizer
      dockerfile: Dockerfile
      target: development
    container_name: sdtlviz_webdev
    profiles:
      - development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # If you set an invalid key as env var you will need to restart the container
      # - REACT_APP_GOOGLE_API=HIER_YOUR_KEY
    volumes:
      - ./visualizer/src:/app/src
      - ./visualizer/public:/app/public
      - ./visualizer/tsconfig.json:/app/tsconfig.json
      - ./visualizer/package.json:/app/package.json
      - ./visualizer/package-lock.json:/app/package-lock.json
      - /app/node_modules
    stdin_open: true
    networks:
      - sdtlviz_network

  nodered:
    image: nodered/node-red:latest
    container_name: sdtlviz_nodered
    profiles:
      - development
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    networks:
      - sdtlviz_network
    volumes:
      # load flows from local file
      - ./nodered/flows.json:/data/flows.json:rw
      - ./nodered/settings.js:/data/settings.js:rw
      # save data locally under ./src/data/raw
      - ./visualizer/src/data:/usr/src/node-red/logs

  webprod:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    profiles:
      - production
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      # If you set an invalid key as env var you will need to restart the container
      # - REACT_APP_GOOGLE_API=HIER_YOUR_KEY

networks:
  sdtlviz_network:

